// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Zoologico.API.Migrations
{
    [DbContext(typeof(ZoologicoAPIContext))]
    [Migration("20251204125819_new01")]
    partial class new01
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Zoologicos.Modelos.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Edad")
                        .HasColumnType("integer");

                    b.Property<int?>("EspecieCodigo")
                        .HasColumnType("integer");

                    b.Property<int>("EspeciesCodigo")
                        .HasColumnType("integer");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RazaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EspecieCodigo");

                    b.HasIndex("RazaId");

                    b.ToTable("Animal");
                });

            modelBuilder.Entity("Zoologicos.Modelos.Especie", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Codigo"));

                    b.Property<string>("NombreComun")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Codigo");

                    b.ToTable("Especie");
                });

            modelBuilder.Entity("Zoologicos.Modelos.Raza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Raza");
                });

            modelBuilder.Entity("Zoologicos.Modelos.Animal", b =>
                {
                    b.HasOne("Zoologicos.Modelos.Especie", "Especie")
                        .WithMany("Animals")
                        .HasForeignKey("EspecieCodigo");

                    b.HasOne("Zoologicos.Modelos.Raza", "Raza")
                        .WithMany("Animals")
                        .HasForeignKey("RazaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especie");

                    b.Navigation("Raza");
                });

            modelBuilder.Entity("Zoologicos.Modelos.Especie", b =>
                {
                    b.Navigation("Animals");
                });

            modelBuilder.Entity("Zoologicos.Modelos.Raza", b =>
                {
                    b.Navigation("Animals");
                });
#pragma warning restore 612, 618
        }
    }
}
