FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 10000

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Copiamos el .csproj (estás dentro de Zoologico.API, no hay subcarpetas)
COPY ["Zoologico.API.csproj", "./"]
RUN dotnet restore "Zoologico.API.csproj"

# Copiamos todo el código
COPY . .

RUN dotnet build "Zoologico.API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Zoologico.API.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Zoologico.API.dll"]
